=== FranckSilvestre/ReleveNotes-Spring-WS/ReleveNotes-Spring-WS/ReleveNotes-WS/src/main/webapp/WEB-INF/xsd/ReleveNotes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://iaws/ws/contractfirst/exemple" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ReleveNotes" type="exem:ReleveNotesType" xmlns:exem="http://iaws/ws/contractfirst/exemple"/>

    <xs:complexType name="matiereType">
    <xs:all>
      <xs:element name="code">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="IAWS"/>
            <xs:enumeration value="JEE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="libelle">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Interopérabilité Application Web Services"/>
            <xs:enumeration value="Java Entreprise Edition"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:all>
    <xs:attribute type="xs:short" name="id" use="optional"/>
  </xs:complexType>

    <xs:complexType name="etudiantType">
    <xs:all>
      <xs:element name="nom">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Dupont"/>
            <xs:enumeration value="Durand"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="prenom">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Pauline"/>
            <xs:enumeration value="Jules"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:all>
    <xs:attribute type="xs:int" name="id" use="optional"/>
  </xs:complexType>

    <xs:complexType name="evaluationType">
    <xs:all>
      <xs:element type="xs:string" name="titre"/>
      <xs:element type="xs:date" name="date"/>
      <xs:element type="xs:float" name="note"/>
      <xs:element type="xs:float" name="note_max"/>
      <xs:element type="xs:float" name="coefficient"/>
    </xs:all>
    <xs:attribute type="xs:int" name="id" use="required"/>
    <xs:attribute type="xs:int" name="id_etudiant" use="required"/>
    <xs:attribute type="xs:int" name="id_matiere" use="required"/>
  </xs:complexType>

    <xs:complexType name="ReleveNotesType">
    <xs:sequence>
      <xs:element type="exem:etudiantType" name="etudiant" maxOccurs="unbounded" minOccurs="1" xmlns:exem="http://iaws/ws/contractfirst/exemple"/>
      <xs:element type="exem:matiereType" name="matiere" maxOccurs="unbounded" minOccurs="1" xmlns:exem="http://iaws/ws/contractfirst/exemple"/>
      <xs:element type="exem:evaluationType" name="evaluation" maxOccurs="unbounded" minOccurs="1" xmlns:exem="http://iaws/ws/contractfirst/exemple"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="annee_scolaire"/>
    <xs:attribute type="xs:string" name="niveau"/>
    <xs:attribute type="xs:short" name="semestre"/>
  </xs:complexType>

    <xs:element name="ReleveNotesRequest" type="exem:ReleveNotesRequestType" xmlns:exem="http://iaws/ws/contractfirst/exemple"/>

    <xs:complexType name="ReleveNotesRequestType">
        <xs:all>
            <xs:element type="xs:string" name="annee_scolaire"/>
            <xs:element type="xs:string" name="niveau"/>
            <xs:element type="xs:short" name="semestre"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== FranckSilvestre/ReleveNotes-Spring-WS/ReleveNotes-Spring-WS/ReleveNotes-WS/src/main/java/ReleveNotes.xml
<ReleveNotes xmlns="http://iaws/ws/contractfirst/exemple" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://iaws/ws/contractfirst/exemple ReleveNotes.xsd" annee_scolaire="2012-2013" niveau="Master" semestre="2">
    <etudiant id="123456789">
        <nom>Dupont</nom>
        <prenom>Pauline</prenom>
    </etudiant>
    <etudiant id="189246756">
        <nom>Durand</nom>
        <prenom>Jules</prenom>
    </etudiant>
    <matiere id="598">
        <code>IAWS</code>
        <libelle>Interopérabilité Application Web Services</libelle>
    </matiere>
    <matiere id="421">
        <code>JEE</code>
        <libelle>Java Entreprise Edition</libelle>
    </matiere>
    <evaluation id="235" id_etudiant="123456789" id_matiere="421">
        <titre>Evaluation 1</titre>
        <date>2013-01-15</date>
        <note>15.5</note>
        <note_max>20</note_max>
        <coefficient>1</coefficient>
    </evaluation>
    <evaluation id="236" id_etudiant="123456789" id_matiere="598">
        <titre>Evaluation 2</titre>
        <date>2013-01-15</date>
        <note>18</note>
        <note_max>20</note_max>
        <coefficient>0.5</coefficient>
    </evaluation>
    <evaluation id="237" id_etudiant="189246756" id_matiere="421">
        <titre>Evaluation 1</titre>
        <date>2013-01-15</date>
        <note>11</note>
        <note_max>20</note_max>
        <coefficient>1</coefficient>
    </evaluation>
    <evaluation id="238" id_etudiant="189246756" id_matiere="598">
        <titre>Evaluation 2</titre>
        <date>2013-01-15</date>
        <note>14</note>
        <note_max>20</note_max>
        <coefficient>0.5</coefficient>
    </evaluation>
</ReleveNotes>
